version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      DEBUG: "TRUE"
      ONLINE_MODE: "FALSE"
    tty: true
    stdin_open: true
    restart: unless-stopped
